import { screen, within, fireEvent, act } from "@testing-library/react"
import { goTo, installBridge, setup, signIn } from "./helpers"

async function signedIn() {
  const utils = setup()
  await signIn(utils.user)
  return utils
}

describe("AppShell: in-app menu bar (browser preview)", () => {
  test("menus open with the mouse and run their actions", async () => {
    const { user } = await signedIn()
    const menubar = screen.getByRole("menubar", { name: /application menu/i })
    await user.click(within(menubar).getByRole("menuitem", { name: "View" }))
    const viewMenu = screen.getByRole("menu", { name: "View menu" })
    await user.click(within(viewMenu).getByRole("menuitem", { name: /activity/i }))
    expect(screen.getByRole("heading", { name: /activity log/i })).toBeInTheDocument()
    expect(screen.queryByRole("menu", { name: "View menu" })).not.toBeInTheDocument()
  })

  test("menus are fully keyboard operable", async () => {
    const { user } = await signedIn()
    const fileButton = within(screen.getByRole("menubar")).getByRole("menuitem", { name: "File" })
    fileButton.focus()
    await user.keyboard("{ArrowDown}")
    const fileMenu = await screen.findByRole("menu", { name: "File menu" })
    const items = within(fileMenu).getAllByRole("menuitem")
    await act(async () => new Promise((r) => setTimeout(r, 0)))
    expect(items[0]).toHaveFocus()
    await user.keyboard("{ArrowDown}")
    expect(items[1]).toHaveFocus()
    await user.keyboard("{ArrowUp}{ArrowUp}")
    expect(items[items.length - 1]).toHaveFocus()
    await user.keyboard("{Home}")
    expect(items[0]).toHaveFocus()
    await user.keyboard("{End}")
    expect(items[items.length - 1]).toHaveFocus()
    await user.keyboard("{ArrowRight}")
    expect(await screen.findByRole("menu", { name: "Edit menu" })).toBeInTheDocument()
    await user.keyboard("{ArrowLeft}")
    expect(await screen.findByRole("menu", { name: "File menu" })).toBeInTheDocument()
    await user.keyboard("{Escape}")
    expect(screen.queryByRole("menu", { name: "File menu" })).not.toBeInTheDocument()
    // Clicking elsewhere closes an open menu.
    await user.click(within(screen.getByRole("menubar")).getByRole("menuitem", { name: "Help" }))
    expect(screen.getByRole("menu", { name: "Help menu" })).toBeInTheDocument()
    await user.click(screen.getByRole("main"))
    expect(screen.queryByRole("menu", { name: "Help menu" })).not.toBeInTheDocument()
    // Enter also opens a menu; Tab closes it.
    within(screen.getByRole("menubar")).getByRole("menuitem", { name: "Edit" }).focus()
    await user.keyboard("{Enter}")
    expect(await screen.findByRole("menu", { name: "Edit menu" })).toBeInTheDocument()
    await user.keyboard("{Tab}")
    expect(screen.queryByRole("menu", { name: "Edit menu" })).not.toBeInTheDocument()
  })

  test("browser keyboard shortcuts: F1, Ctrl+, Ctrl+F, Ctrl+N, zoom", async () => {
    const { user } = await signedIn()
    await user.keyboard("{F1}")
    expect(screen.getByRole("dialog", { name: /keyboard shortcuts/i })).toBeInTheDocument()
    await user.click(screen.getByRole("button", { name: /close keyboard shortcuts/i }))
    await user.keyboard("{Control>},{/Control}")
    expect(screen.getByRole("dialog", { name: /settings/i })).toBeInTheDocument()
    await user.click(screen.getByRole("button", { name: /close settings/i }))
    await user.keyboard("{Control>}f{/Control}")
    expect(screen.getByRole("search")).toBeInTheDocument()
    await user.keyboard("{Escape}")
    expect(screen.queryByRole("search")).not.toBeInTheDocument()
    await user.keyboard("{Control>}n{/Control}")
    expect(screen.getByText(/Messages opened/)).toBeInTheDocument()
    await user.keyboard("{Control>}={/Control}{Control>}={/Control}")
    expect(screen.getByText(/Zoom 125%/)).toBeInTheDocument()
    await user.keyboard("{Control>}-{/Control}")
    expect(screen.getByText(/Zoom 110%/)).toBeInTheDocument()
    await user.keyboard("{Control>}0{/Control}")
    expect(screen.getByText(/Zoom 100%/)).toBeInTheDocument()
  })
})

describe("AppShell: search, settings and dialogs", () => {
  test("search finds medications, appointments and messages", async () => {
    const { user } = await signedIn()
    await user.click(screen.getByRole("button", { name: /search careconnect/i }))
    const box = screen.getByRole("textbox", { name: /search careconnect/i })
    await user.type(box, "zzzz")
    expect(screen.getByText(/No matches for zzzz/)).toBeInTheDocument()
    await user.clear(box)
    await user.type(box, "amlodipine")
    const results = within(screen.getByRole("region", { name: /search results/i }))
    expect(results.getAllByRole("button").length).toBeGreaterThan(0)
    await user.click(results.getAllByRole("button")[0])
    expect(screen.getByText(/^Opened /)).toBeInTheDocument()
    await user.keyboard("{Control>}f{/Control}")
    await user.type(screen.getByRole("textbox", { name: /search careconnect/i }), "eye{Enter}")
    expect(screen.getByRole("heading", { name: /manage appointments/i })).toBeInTheDocument()
  })

  test("settings: theme, text size, high contrast, hand mode and sections", async () => {
    const { user, container } = await signedIn()
    await user.click(screen.getByRole("button", { name: /open settings/i }))
    const dialog = screen.getByRole("dialog", { name: /settings/i })
    await user.click(within(dialog).getByRole("button", { name: "dark" }))
    expect(document.documentElement).toHaveClass("dark")
    expect(localStorage.getItem("cc-theme")).toBe("dark")
    await user.click(within(dialog).getByRole("button", { name: "light" }))
    expect(document.documentElement).not.toHaveClass("dark")
    await user.click(within(dialog).getByRole("button", { name: "Extra large" }))
    expect(document.documentElement.style.fontSize).toBe("22px")
    await user.click(within(dialog).getByRole("button", { name: "large" }))
    expect(document.documentElement.style.fontSize).toBe("19px")

    await user.click(within(dialog).getByRole("button", { name: /^accessibility/i }))
    await user.click(within(dialog).getByRole("switch"))
    expect(document.documentElement).toHaveClass("high-contrast")
    await user.click(within(dialog).getByRole("button", { name: "Left-hand" }))
    expect(container.querySelector(".desktop-window")).toHaveClass("hand-left")
    await user.click(within(dialog).getByRole("button", { name: "Right-hand" }))
    expect(container.querySelector(".desktop-window")).toHaveClass("hand-right")
    await user.click(within(dialog).getByRole("button", { name: "Standard" }))

    await user.click(within(dialog).getByRole("button", { name: /data & storage/i }))
    expect(within(dialog).getByText(/browser preview does not save/i)).toBeInTheDocument()
    await user.click(within(dialog).getByRole("button", { name: "Save now" }))
    await user.click(within(dialog).getByRole("button", { name: "Done" }))
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument()
  })

  test("desktop settings offer export and import", async () => {
    const bridge = installBridge()
    const { user } = await signedIn()
    bridge.emitMenu("settings")
    const dialog = screen.getByRole("dialog", { name: /settings/i })
    await user.click(within(dialog).getByRole("button", { name: /data & storage/i }))
    expect(within(dialog).getByText(/saves the care plan on this computer/i)).toBeInTheDocument()
    await user.click(within(dialog).getByRole("button", { name: "Export…" }))
    expect(bridge.exportCareData).toHaveBeenCalled()
    await user.click(within(dialog).getByRole("button", { name: "Import…" }))
    expect(bridge.importCareData).toHaveBeenCalled()
    await user.click(within(dialog).getByRole("button", { name: "Sign out" }))
    expect(await screen.findByText(/one calm workspace/i)).toBeInTheDocument()
  })

  test("keyboard shortcuts dialog can be printed", async () => {
    const print = jest.spyOn(window, "print").mockImplementation(() => undefined)
    const { user } = await signedIn()
    await user.keyboard("{F1}")
    const dialog = screen.getByRole("dialog", { name: /keyboard shortcuts/i })
    expect(within(dialog).getByText("Export care plan")).toBeInTheDocument()
    expect(within(dialog).getByText("Navigate to Page (Overview through Messages)")).toBeInTheDocument()
    expect(within(dialog).getByText("Messages Menu")).toBeInTheDocument()
    await user.click(within(dialog).getByRole("button", { name: /print reference/i }))
    expect(print).toHaveBeenCalled()
    await user.click(within(dialog).getByRole("button", { name: "Done" }))
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument()
  })

  test("emergency prompt: SOS call shows a (demo) call in progress, then ends", async () => {
    const { user } = await signedIn()
    await user.click(screen.getByRole("button", { name: /emergency/i }))
    let dialog = screen.getByRole("alertdialog", { name: "Emergency" })
    expect(dialog).toHaveTextContent(/call emergency services immediately/i)
    await user.click(within(dialog).getByRole("button", { name: "Cancel" }))
    expect(screen.queryByRole("alertdialog")).not.toBeInTheDocument()

    await user.click(screen.getByRole("button", { name: /emergency/i }))
    dialog = screen.getByRole("alertdialog", { name: "Emergency" })
    await user.click(within(dialog).getByRole("button", { name: /sos emergency call/i }))
    dialog = screen.getByRole("alertdialog", { name: /calling 911/i })
    expect(dialog).toHaveTextContent(/connecting to emergency services/i)
    expect(screen.getByText("Emergency call in progress")).toBeInTheDocument()
    await user.click(within(dialog).getByRole("button", { name: "End call" }))
    expect(screen.queryByRole("alertdialog")).not.toBeInTheDocument()
    expect(screen.getByText("Emergency call ended")).toBeInTheDocument()
  })

  test("care recipient switcher lists Margaret and closes with Escape", async () => {
    const { user } = await signedIn()
    const switcher = screen.getByRole("button", { name: /switch care recipient/i })
    expect(switcher).toHaveAttribute("aria-expanded", "false")
    await user.click(switcher)
    const menu = screen.getByRole("menu", { name: "Care recipients" })
    const option = within(menu).getByRole("menuitemradio", { name: /margaret thompson/i })
    expect(option).toHaveAttribute("aria-checked", "true")
    await user.click(option)
    expect(screen.queryByRole("menu", { name: "Care recipients" })).not.toBeInTheDocument()
    expect(screen.getByText("Viewing Margaret Thompson's care plan")).toBeInTheDocument()

    switcher.focus()
    await user.keyboard("{ArrowDown}")
    expect(screen.getByRole("menu", { name: "Care recipients" })).toBeInTheDocument()
    await user.keyboard("{Escape}")
    expect(screen.queryByRole("menu", { name: "Care recipients" })).not.toBeInTheDocument()
    expect(switcher).toHaveFocus()

    await user.click(switcher)
    await user.click(document.body)
    expect(screen.queryByRole("menu", { name: "Care recipients" })).not.toBeInTheDocument()
  })

  test("account menu opens settings or signs out, and closes with Escape", async () => {
    const { user } = await signedIn()
    const account = screen.getByRole("button", { name: /account menu, signed in as jane roe/i })
    await user.click(account)
    const menu = screen.getByRole("menu", { name: "Account" })
    await user.click(within(menu).getByRole("menuitem", { name: /settings/i }))
    expect(screen.getByRole("dialog", { name: /settings/i })).toBeInTheDocument()
    await user.keyboard("{Escape}")
    account.focus()
    await user.keyboard("{ArrowDown}")
    expect(screen.getByRole("menu", { name: "Account" })).toBeInTheDocument()
    await user.keyboard("{Escape}")
    expect(screen.queryByRole("menu", { name: "Account" })).not.toBeInTheDocument()
    await user.click(account)
    await user.click(screen.getByRole("main"))
    expect(screen.queryByRole("menu", { name: "Account" })).not.toBeInTheDocument()
    account.focus()
    await user.keyboard("{ArrowDown}")
    await act(async () => new Promise((r) => setTimeout(r, 0)))
    await user.keyboard("{Tab}")
    expect(screen.queryByRole("menu", { name: "Account" })).not.toBeInTheDocument()
    await user.click(account)
    await user.click(within(screen.getByRole("menu", { name: "Account" })).getByRole("menuitem", { name: /sign out/i }))
    expect(await screen.findByText(/one calm workspace/i)).toBeInTheDocument()
  })

  test("right-click and keyboard context menu", async () => {
    const { user } = await signedIn()
    await goTo(user, "Medications")
    fireEvent.contextMenu(screen.getByRole("main"), { clientX: 200, clientY: 200 })
    let menu = screen.getByRole("menu", { name: "Context menu" })
    await user.click(within(menu).getByRole("menuitem", { name: /open overview/i }))
    expect(screen.getByRole("heading", { name: /margaret's status today/i })).toBeInTheDocument()
    // Shift+F10 / context-menu key produce a 0,0 event.
    fireEvent.contextMenu(screen.getByRole("main"), { clientX: 0, clientY: 0 })
    menu = screen.getByRole("menu", { name: "Context menu" })
    await user.click(within(menu).getByRole("menuitem", { name: /refresh care plan/i }))
    expect(screen.getByText("Care plan refreshed")).toBeInTheDocument()
    fireEvent.contextMenu(screen.getByRole("main"))
    await user.click(within(screen.getByRole("menu", { name: "Context menu" })).getByRole("menuitem", { name: /settings/i }))
    expect(screen.getByRole("dialog", { name: /settings/i })).toBeInTheDocument()
    await user.keyboard("{Escape}")
    fireEvent.contextMenu(screen.getByRole("main"))
    await user.click(screen.getByRole("main"))
    expect(screen.queryByRole("menu", { name: "Context menu" })).not.toBeInTheDocument()
  })

  test("toolbar buttons and sidebar navigation", async () => {
    const { user } = await signedIn()
    await user.click(screen.getByRole("button", { name: /open medications/i }))
    expect(screen.getByRole("heading", { name: /manage medications/i })).toBeInTheDocument()
    await user.click(screen.getByRole("button", { name: /open appointments/i }))
    expect(screen.getByRole("heading", { name: /manage appointments/i })).toBeInTheDocument()
    await user.click(screen.getByRole("button", { name: /new message/i }))
    expect(screen.getByRole("heading", { name: "New Message" })).toBeInTheDocument()
    await user.click(screen.getByRole("button", { name: /save care plan/i }))
    await goTo(user, "Activity")
    const nav = screen.getByRole("navigation", { name: /main navigation/i })
    expect(within(nav).getByRole("button", { name: /activity/i })).toHaveAttribute("aria-current", "page")
    await user.click(screen.getByRole("button", { name: /^settings/i }))
    expect(screen.getByRole("dialog", { name: /settings/i })).toBeInTheDocument()
  })

  test("skip link targets the main content", async () => {
    await signedIn()
    expect(screen.getByRole("link", { name: /skip to main content/i })).toHaveAttribute("href", "#main-content")
    expect(screen.getByRole("main")).toHaveAttribute("id", "main-content")
  })
})
